/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Roboto Mono Medium24.c                                *
* Font:        Roboto Mono Medium                                    *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x21 (33)                                     *
* Character enabled:   0x22 (34)                                     *
* Character enabled:   0x23 (35)                                     *
* Character enabled:   0x24 (36)                                     *
* Character enabled:   0x25 (37)                                     *
* Character enabled:   0x27 (39)                                     *
* Character enabled:   0x7 (7)                                       *
* Character disabled:  0x7 (7)                                       *
* Character enabled:   0x26 (38)                                     *
* Character enabled:   0x28 (40)                                     *
* Character enabled:   0x29 (41)                                     *
* Character enabled:   0x2A (42)                                     *
* Character enabled:   0x2B (43)                                     *
* Character enabled:   0x2C (44)                                     *
* Character enabled:   0x2D (45)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x2F (47)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x3A (58)                                     *
* Character enabled:   0x3B (59)                                     *
* Character enabled:   0x3C (60)                                     *
* Character enabled:   0x3D (61)                                     *
* Character enabled:   0x3E (62)                                     *
* Character enabled:   0x3F (63)                                     *
* Character enabled:   0x40 (64)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x42 (66)                                     *
* Character enabled:   0x43 (67)                                     *
* Character enabled:   0x44 (68)                                     *
* Character enabled:   0x45 (69)                                     *
* Character enabled:   0x46 (70)                                     *
* Character enabled:   0x47 (71)                                     *
* Character enabled:   0x48 (72)                                     *
* Character enabled:   0x49 (73)                                     *
* Character enabled:   0x4A (74)                                     *
* Character enabled:   0x4B (75)                                     *
* Character enabled:   0x4C (76)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x4E (78)                                     *
* Character enabled:   0x4F (79)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x51 (81)                                     *
* Character enabled:   0x52 (82)                                     *
* Character enabled:   0x53 (83)                                     *
* Character enabled:   0x54 (84)                                     *
* Character enabled:   0x55 (85)                                     *
* Character enabled:   0x56 (86)                                     *
* Character enabled:   0x57 (87)                                     *
* Character enabled:   0x58 (88)                                     *
* Character enabled:   0x59 (89)                                     *
* Character enabled:   0x5A (90)                                     *
* Character enabled:   0x5B (91)                                     *
* Character enabled:   0x5C (92)                                     *
* Character enabled:   0x5D (93)                                     *
* Character enabled:   0x5E (94)                                     *
* Character enabled:   0x5F (95)                                     *
* Character enabled:   0x60 (96)                                     *
* Character enabled:   0x61 (97)                                     *
* Character enabled:   0x62 (98)                                     *
* Character enabled:   0x63 (99)                                     *
* Character enabled:   0x64 (100)                                    *
* Character enabled:   0x65 (101)                                    *
* Character enabled:   0x66 (102)                                    *
* Character enabled:   0x67 (103)                                    *
* Character enabled:   0x68 (104)                                    *
* Character enabled:   0x69 (105)                                    *
* Character enabled:   0x6A (106)                                    *
* Character enabled:   0x6B (107)                                    *
* Character enabled:   0x6C (108)                                    *
* Character enabled:   0x6D (109)                                    *
* Character enabled:   0x6E (110)                                    *
* Character enabled:   0x6F (111)                                    *
* Character enabled:   0x70 (112)                                    *
* Character enabled:   0x71 (113)                                    *
* Character enabled:   0x72 (114)                                    *
* Character enabled:   0x73 (115)                                    *
* Character enabled:   0x74 (116)                                    *
* Character enabled:   0x75 (117)                                    *
* Character enabled:   0x76 (118)                                    *
* Character enabled:   0x77 (119)                                    *
* Character enabled:   0x78 (120)                                    *
* Character enabled:   0x79 (121)                                    *
* Character enabled:   0x7A (122)                                    *
* Character enabled:   0x7B (123)                                    *
* Character enabled:   0x7C (124)                                    *
* Character enabled:   0x7D (125)                                    *
* Character enabled:   0x7E (126)                                    *
*                                                                    *
**********************************************************************
*/
#define	________	0x0
#define	_______X	0x1
#define	______X_	0x2
#define	______XX	0x3
#define	_____X__	0x4
#define	_____X_X	0x5
#define	_____XX_	0x6
#define	_____XXX	0x7
#define	____X___	0x8
#define	____X__X	0x9
#define	____X_X_	0xa
#define	____X_XX	0xb
#define	____XX__	0xc
#define	____XX_X	0xd
#define	____XXX_	0xe
#define	____XXXX	0xf
#define	___X____	0x10
#define	___X___X	0x11
#define	___X__X_	0x12
#define	___X__XX	0x13
#define	___X_X__	0x14
#define	___X_X_X	0x15
#define	___X_XX_	0x16
#define	___X_XXX	0x17
#define	___XX___	0x18
#define	___XX__X	0x19
#define	___XX_X_	0x1a
#define	___XX_XX	0x1b
#define	___XXX__	0x1c
#define	___XXX_X	0x1d
#define	___XXXX_	0x1e
#define	___XXXXX	0x1f
#define	__X_____	0x20
#define	__X____X	0x21
#define	__X___X_	0x22
#define	__X___XX	0x23
#define	__X__X__	0x24
#define	__X__X_X	0x25
#define	__X__XX_	0x26
#define	__X__XXX	0x27
#define	__X_X___	0x28
#define	__X_X__X	0x29
#define	__X_X_X_	0x2a
#define	__X_X_XX	0x2b
#define	__X_XX__	0x2c
#define	__X_XX_X	0x2d
#define	__X_XXX_	0x2e
#define	__X_XXXX	0x2f
#define	__XX____	0x30
#define	__XX___X	0x31
#define	__XX__X_	0x32
#define	__XX__XX	0x33
#define	__XX_X__	0x34
#define	__XX_X_X	0x35
#define	__XX_XX_	0x36
#define	__XX_XXX	0x37
#define	__XXX___	0x38
#define	__XXX__X	0x39
#define	__XXX_X_	0x3a
#define	__XXX_XX	0x3b
#define	__XXXX__	0x3c
#define	__XXXX_X	0x3d
#define	__XXXXX_	0x3e
#define	__XXXXXX	0x3f
#define	_X______	0x40
#define	_X_____X	0x41
#define	_X____X_	0x42
#define	_X____XX	0x43
#define	_X___X__	0x44
#define	_X___X_X	0x45
#define	_X___XX_	0x46
#define	_X___XXX	0x47
#define	_X__X___	0x48
#define	_X__X__X	0x49
#define	_X__X_X_	0x4a
#define	_X__X_XX	0x4b
#define	_X__XX__	0x4c
#define	_X__XX_X	0x4d
#define	_X__XXX_	0x4e
#define	_X__XXXX	0x4f
#define	_X_X____	0x50
#define	_X_X___X	0x51
#define	_X_X__X_	0x52
#define	_X_X__XX	0x53
#define	_X_X_X__	0x54
#define	_X_X_X_X	0x55
#define	_X_X_XX_	0x56
#define	_X_X_XXX	0x57
#define	_X_XX___	0x58
#define	_X_XX__X	0x59
#define	_X_XX_X_	0x5a
#define	_X_XX_XX	0x5b
#define	_X_XXX__	0x5c
#define	_X_XXX_X	0x5d
#define	_X_XXXX_	0x5e
#define	_X_XXXXX	0x5f
#define	_XX_____	0x60
#define	_XX____X	0x61
#define	_XX___X_	0x62
#define	_XX___XX	0x63
#define	_XX__X__	0x64
#define	_XX__X_X	0x65
#define	_XX__XX_	0x66
#define	_XX__XXX	0x67
#define	_XX_X___	0x68
#define	_XX_X__X	0x69
#define	_XX_X_X_	0x6a
#define	_XX_X_XX	0x6b
#define	_XX_XX__	0x6c
#define	_XX_XX_X	0x6d
#define	_XX_XXX_	0x6e
#define	_XX_XXXX	0x6f
#define	_XXX____	0x70
#define	_XXX___X	0x71
#define	_XXX__X_	0x72
#define	_XXX__XX	0x73
#define	_XXX_X__	0x74
#define	_XXX_X_X	0x75
#define	_XXX_XX_	0x76
#define	_XXX_XXX	0x77
#define	_XXXX___	0x78
#define	_XXXX__X	0x79
#define	_XXXX_X_	0x7a
#define	_XXXX_XX	0x7b
#define	_XXXXX__	0x7c
#define	_XXXXX_X	0x7d
#define	_XXXXXX_	0x7e
#define	_XXXXXXX	0x7f
#define	X_______	0x80
#define	X______X	0x81
#define	X_____X_	0x82
#define	X_____XX	0x83
#define	X____X__	0x84
#define	X____X_X	0x85
#define	X____XX_	0x86
#define	X____XXX	0x87
#define	X___X___	0x88
#define	X___X__X	0x89
#define	X___X_X_	0x8a
#define	X___X_XX	0x8b
#define	X___XX__	0x8c
#define	X___XX_X	0x8d
#define	X___XXX_	0x8e
#define	X___XXXX	0x8f
#define	X__X____	0x90
#define	X__X___X	0x91
#define	X__X__X_	0x92
#define	X__X__XX	0x93
#define	X__X_X__	0x94
#define	X__X_X_X	0x95
#define	X__X_XX_	0x96
#define	X__X_XXX	0x97
#define	X__XX___	0x98
#define	X__XX__X	0x99
#define	X__XX_X_	0x9a
#define   X__XX_XX	0x9b
#define   X__XXX__	0x9c
#define   X__XXX_X	0x9d
#define	X__XXXX_	0x9e
#define	X__XXXXX	0x9f
#define	X_X_____	0xa0
#define	X_X____X	0xa1
#define	X_X___X_	0xa2
#define	X_X___XX	0xa3
#define	X_X__X__	0xa4
#define	X_X__X_X	0xa5
#define	X_X__XX_	0xa6
#define	X_X__XXX	0xa7
#define	X_X_X___	0xa8
#define	X_X_X__X	0xa9
#define	X_X_X_X_	0xaa
#define	X_X_X_XX	0xab
#define	X_X_XX__	0xac
#define	X_X_XX_X	0xad
#define	X_X_XXX_	0xae
#define	X_X_XXXX	0xaf
#define	X_XX____	0xb0
#define	X_XX___X	0xb1
#define	X_XX__X_	0xb2
#define	X_XX__XX	0xb3
#define	X_XX_X__	0xb4
#define	X_XX_X_X	0xb5
#define	X_XX_XX_	0xb6
#define	X_XX_XXX	0xb7
#define	X_XXX___	0xb8
#define	X_XXX__X	0xb9
#define	X_XXX_X_	0xba
#define	X_XXX_XX	0xbb
#define	X_XXXX__	0xbc
#define	X_XXXX_X	0xbd
#define	X_XXXXX_	0xbe
#define	X_XXXXXX	0xbf
#define	XX______	0xc0
#define	XX_____X	0xc1
#define	XX____X_	0xc2
#define	XX____XX	0xc3
#define	XX___X__	0xc4
#define	XX___X_X	0xc5
#define	XX___XX_	0xc6
#define	XX___XXX	0xc7
#define	XX__X___	0xc8
#define	XX__X__X	0xc9
#define	XX__X_X_	0xca
#define	XX__X_XX	0xcb
#define	XX__XX__	0xcc
#define	XX__XX_X	0xcd
#define	XX__XXX_	0xce
#define	XX__XXXX	0xcf
#define	XX_X____	0xd0
#define	XX_X___X	0xd1
#define	XX_X__X_	0xd2
#define	XX_X__XX	0xd3
#define	XX_X_X__	0xd4
#define	XX_X_X_X	0xd5
#define	XX_X_XX_	0xd6
#define	XX_X_XXX	0xd7
#define	XX_XX___	0xd8
#define	XX_XX__X	0xd9
#define	XX_XX_X_	0xda
#define	XX_XX_XX	0xdb
#define	XX_XXX__	0xdc
#define	XX_XXX_X	0xdd
#define	XX_XXXX_	0xde
#define	XX_XXXXX	0xdf
#define	XXX_____	0xe0
#define	XXX____X	0xe1
#define	XXX___X_	0xe2
#define	XXX___XX	0xe3
#define	XXX__X__	0xe4
#define	XXX__X_X	0xe5
#define	XXX__XX_	0xe6
#define	XXX__XXX	0xe7
#define	XXX_X___	0xe8
#define	XXX_X__X	0xe9
#define	XXX_X_X_	0xea
#define	XXX_X_XX	0xeb
#define	XXX_XX__	0xec
#define	XXX_XX_X	0xed
#define	XXX_XXX_	0xee
#define	XXX_XXXX	0xef
#define	XXXX____	0xf0
#define	XXXX___X	0xf1
#define	XXXX__X_	0xf2
#define	XXXX__XX	0xf3
#define	XXXX_X__	0xf4
#define	XXXX_X_X	0xf5
#define	XXXX_XX_	0xf6
#define	XXXX_XXX	0xf7
#define	XXXXX___	0xf8
#define	XXXXX__X	0xf9
#define	XXXXX_X_	0xfa
#define	XXXXX_XX	0xfb
#define	XXXXXX__	0xfc
#define	XXXXXX_X	0xfd
#define	XXXXXXX_	0xfe
#define	XXXXXXXX	0xff

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0020[ 48] = { /* code 0020, SPACE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0021[ 48] = { /* code 0021, EXCLAMATION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0022[ 48] = { /* code 0022, QUOTATION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X__XX,________,
  ___X__XX,________,
  ___X__XX,________,
  ___X__XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0023[ 48] = { /* code 0023, NUMBER SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,X_______,
  ____X__X,X_______,
  ____X__X,X_______,
  ____X__X,________,
  _XXXXXXX,XX______,
  ___XX__X,________,
  ___X__XX,________,
  ___X__XX,________,
  XXXXXXXX,XX______,
  __XX__X_,________,
  __XX__X_,________,
  __XX__X_,________,
  __X__XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0024[ 48] = { /* code 0024, DOLLAR SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  ____XXXX,________,
  __XXXXXX,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  __XX____,________,
  __XXXX__,________,
  ___XXXXX,________,
  _____XXX,X_______,
  _______X,XX______,
  _XX_____,XX______,
  _XXX____,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0025[ 48] = { /* code 0025, PERCENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _X_XX___,________,
  XX__X__X,X_______,
  XX__X_XX,________,
  _XXXX_X_,________,
  __XX_XX_,________,
  _____X__,________,
  ____XX__,________,
  ____X_XX,XX______,
  ___XX_X_,_X______,
  __XX__X_,_X______,
  ______X_,_X______,
  ______XX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0026[ 48] = { /* code 0026, AMPERSAND */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX_XXX,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,_X______,
  _XX__XX_,XX______,
  _XX___XX,XX______,
  _XX___XX,X_______,
  _XXXXXXX,XX______,
  __XXXXX_,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0027[ 48] = { /* code 0027, APOSTROPHE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0028[ 48] = { /* code 0028, LEFT PARENTHESIS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  _____XX_,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ____X___,________,
  ____XX__,________,
  ____XX__,________,
  _____XX_,________,
  ______X_,________,
  _______X,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0029[ 48] = { /* code 0029, RIGHT PARENTHESIS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,________,
  ___XX___,________,
  ____XX__,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  ____XX__,________,
  ___XX___,________,
  ___X____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002A[ 48] = { /* code 002A, ASTERISK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  __XX_X__,XX______,
  _XXXXXXX,X_______,
  ____XXX_,________,
  ____X_XX,________,
  __XXX__X,X_______,
  ___X___X,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002B[ 48] = { /* code 002B, PLUS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002C[ 48] = { /* code 002C, COMMA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002D[ 48] = { /* code 002D, HYPHEN-MINUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002E[ 48] = { /* code 002E, FULL STOP */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_002F[ 48] = { /* code 002F, SOLIDUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0030[ 48] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX____X,XX______,
  _XX___XX,XX______,
  _XX__XXX,XX______,
  _XXXX__X,XX______,
  _XXX___X,XX______,
  _XX____X,X_______,
  __XX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0031[ 48] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ___XXXX_,________,
  __XXXXX_,________,
  __X__XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0032[ 48] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _______X,X_______,
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0033[ 48] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _______X,X_______,
  ______XX,________,
  ____XXX_,________,
  ______XX,X_______,
  _______X,X_______,
  _______X,X_______,
  _XX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0034[ 48] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0035[ 48] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXXX,________,
  __XX__XX,X_______,
  _______X,X_______,
  ________,XX______,
  ________,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0036[ 48] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,________,
  ___XXXXX,________,
  __XXX___,________,
  __XX____,________,
  _XX_____,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XX____X,X_______,
  _XX____X,XX______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0037[ 48] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XXX__,________,
  ___XX___,________,
  __XXX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0038[ 48] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XXX___X,X_______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  __XX__XX,X_______,
  _XX____X,X_______,
  _XX____X,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0039[ 48] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXX_X,X_______,
  _______X,X_______,
  ______XX,________,
  ___XXXXX,________,
  ___XXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003A[ 48] = { /* code 003A, COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003B[ 48] = { /* code 003B, SEMICOLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003C[ 48] = { /* code 003C, LESS-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  ______XX,X_______,
  ____XXXX,X_______,
  __XXXX__,________,
  _XXX____,________,
  __XXXX__,________,
  ____XXXX,X_______,
  _______X,X_______,
  ________,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003D[ 48] = { /* code 003D, EQUALS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003E[ 48] = { /* code 003E, GREATER-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,________,
  _XXX____,________,
  __XXXXX_,________,
  _____XXX,X_______,
  _______X,X_______,
  ____XXXX,X_______,
  _XXXXX__,________,
  _XXX____,________,
  _X______,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_003F[ 48] = { /* code 003F, QUESTION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _______X,XX______,
  _______X,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0040[ 48] = { /* code 0040, COMMERCIAL AT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XXXXX,X_______,
  __X_____,XX______,
  _XX_XXXX,_X______,
  _X__X_XX,_X______,
  _X_XX_XX,_X______,
  XX_X__XX,_X______,
  XX_X__X_,_X______,
  _X_X__X_,_X______,
  _X_XXXXX,X_______,
  _XX_____,________,
  __XX___X,________,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0041[ 48] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____X_XX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  __XX___X,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  XXX_____,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0042[ 48] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  _XXXXXXX,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX___XX,X_______,
  _XXXXXXX,________,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0043[ 48] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,XX______,
  _XX_____,XX______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,XX______,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0044[ 48] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XX____X,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0045[ 48] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0046[ 48] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0047[ 48] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,XX______,
  _XX_____,XX______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX____,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0048[ 48] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXXXXXX,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0049[ 48] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004A[ 48] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004B[ 48] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XXX_____,
  _XX____X,XX______,
  _XX___XX,X_______,
  _XX___XX,________,
  _XX__XX_,________,
  _XX_XX__,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXX_XXX,________,
  _XX___XX,X_______,
  _XX____X,X_______,
  _XX____X,XX______,
  _XX_____,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004C[ 48] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004D[ 48] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXX_XX,XX______,
  _XXXX_X_,XX______,
  _XX_XXX_,XX______,
  _XX_XXX_,XX______,
  _XX_XX__,XX______,
  _XX__X__,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004E[ 48] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX____X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  _XXXX__X,XX______,
  _XX_XX_X,XX______,
  _XX_XX_X,XX______,
  _XX__XXX,XX______,
  _XX__XXX,XX______,
  _XX___XX,XX______,
  _XX___XX,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_004F[ 48] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,X_______,
  _XXX___X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0050[ 48] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXX___X,XX______,
  _XXX____,XX______,
  _XXX____,XX______,
  _XXX____,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0051[ 48] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,X_______,
  _XXX___X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  _______X,XXX_____,
  ________,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0052[ 48] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  _XXXXXXX,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  _XX___XX,________,
  _XX___XX,X_______,
  _XX____X,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0053[ 48] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XX_____,XX______,
  _XXX____,________,
  __XXXX__,________,
  ___XXXXX,________,
  _____XXX,X_______,
  ________,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  __XXXXXX,XX______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0054[ 48] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0055[ 48] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0056[ 48] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XXX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX__XX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  ___XXXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0057[ 48] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___X__,_XX_____,
  _XX_XX__,XX______,
  _XX_XXX_,XX______,
  _XX_XXX_,XX______,
  _XX_XXX_,XX______,
  _XX_X_X_,XX______,
  _XX_X_X_,XX______,
  _XXXX_X_,XX______,
  _XXXX_XX,X_______,
  __XXX_XX,X_______,
  __XX__XX,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0058[ 48] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XX_XX,________,
  ___XX_XX,X_______,
  __XX___X,X_______,
  _XXX___X,XX______,
  XXX_____,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0059[ 48] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX_____,XX______,
  _XX_____,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XXX_XX,________,
  ___XX_XX,________,
  ___XXXX_,________,
  ____XXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005A[ 48] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _______X,X_______,
  ______XX,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  __XXX___,________,
  __XX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005B[ 48] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005C[ 48] = { /* code 005C, REVERSE SOLIDUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  ___X____,________,
  ___XX___,________,
  ___XX___,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ______XX,________,
  ______XX,________,
  _______X,________,
  _______X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005D[ 48] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005E[ 48] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  ____XXX_,________,
  ____X_X_,________,
  ___XX_XX,________,
  ___XX_XX,________,
  ___X___X,________,
  __XX___X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_005F[ 48] = { /* code 005F, LOW LINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0060[ 48] = { /* code 0060, GRAVE ACCENT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0061[ 48] = { /* code 0061, LATIN SMALL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  __XXXXXX,________,
  _XXX___X,X_______,
  _______X,X_______,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0062[ 48] = { /* code 0062, LATIN SMALL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XX_,________,
  _XXXXXXX,X_______,
  _XXX___X,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX___X,X_______,
  _XXXXXXX,X_______,
  _XX_XXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0063[ 48] = { /* code 0063, LATIN SMALL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0064[ 48] = { /* code 0064, LATIN SMALL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ____XX_X,X_______,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0065[ 48] = { /* code 0065, LATIN SMALL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XXXXX,X_______,
  __XX___X,X_______,
  _XX_____,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XX_____,________,
  _XXX____,X_______,
  __XXXXXX,XX______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0066[ 48] = { /* code 0066, LATIN SMALL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0067[ 48] = { /* code 0067, LATIN SMALL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,X_______,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  _______X,X_______,
  __X____X,X_______,
  __XXXXXX,________,
  ____XXX_,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0068[ 48] = { /* code 0068, LATIN SMALL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,________,
  _XX_XXXX,X_______,
  _XXX___X,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0069[ 48] = { /* code 0069, LATIN SMALL LETTER I */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  __XXXXX_,________,
  __XXXXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006A[ 48] = { /* code 006A, LATIN SMALL LETTER J */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ___XXXX_,________,
  ___XXXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  __XXXXX_,________,
  __XXXX__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006B[ 48] = { /* code 006B, LATIN SMALL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX____X,XX______,
  _XX___XX,X_______,
  _XX__XXX,________,
  _XX_XXX_,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  _XXX_XXX,________,
  _XX___XX,________,
  _XX____X,X_______,
  _XX____X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006C[ 48] = { /* code 006C, LATIN SMALL LETTER L */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006D[ 48] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_X__X,X_______,
  _XXXXXXX,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  _XX_XX__,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006E[ 48] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,________,
  _XX_XXXX,X_______,
  _XXX___X,X_______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  _XX____X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_006F[ 48] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  __XXXXXX,________,
  __XX___X,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0070[ 48] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XX_,________,
  _XXXXXXX,X_______,
  _XXX___X,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XXX___X,X_______,
  _XXXXXXX,X_______,
  _XX_XXXX,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0071[ 48] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,X_______,
  __XXXXXX,X_______,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0072[ 48] = { /* code 0072, LATIN SMALL LETTER R */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,XX______,
  ___XXXXX,XX______,
  ___XXXX_,_X______,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0073[ 48] = { /* code 0073, LATIN SMALL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  __XX____,_X______,
  __XXXX__,________,
  ___XXXXX,X_______,
  _______X,XX______,
  _XX_____,XX______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0074[ 48] = { /* code 0074, LATIN SMALL LETTER T */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ____XX__,________,
  ____XXXX,X_______,
  _____XXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0075[ 48] = { /* code 0075, LATIN SMALL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  __XX___X,X_______,
  __XXXXXX,X_______,
  ___XXXX_,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0076[ 48] = { /* code 0076, LATIN SMALL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XX______,
  _XX_____,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,________,
  ___XX_XX,________,
  ___XX_XX,________,
  ___XX_X_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0077[ 48] = { /* code 0077, LATIN SMALL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX___X__,_X______,
  _X__XX__,XX______,
  _XX_XX__,XX______,
  _XX_XXX_,XX______,
  _XX_X_X_,XX______,
  _XX_X_X_,X_______,
  _XXXX_X_,X_______,
  __XX__XX,X_______,
  __XX__XX,X_______,
  __XX___X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0078[ 48] = { /* code 0078, LATIN SMALL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XX______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXXX,________,
  ___XX_XX,________,
  __XX___X,X_______,
  _XXX____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_0079[ 48] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XXX_____,
  _XX_____,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  ___XX_XX,________,
  ___XX_XX,________,
  ____XXX_,________,
  ____XXX_,________,
  _____XX_,________,
  ____XX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_007A[ 48] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_007B[ 48] = { /* code 007B, LEFT CURLY BRACKET */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ___XX___,________,
  ____XX__,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ______XX,________,
  ______XX,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_007C[ 48] = { /* code 007C, VERTICAL LINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_007D[ 48] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XX___,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  _____X__,________,
  _____X__,________,
  _____XX_,________,
  _____XX_,________,
  ______XX,X_______,
  _____XXX,________,
  _____XX_,________,
  _____X__,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontRobotoMonoMedium24_007E[ 48] = { /* code 007E, TILDE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,_X______,
  _XXXXX__,XX______,
  XX___XXX,XX______,
  _______X,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

	
#include <stdint.h>
	
const struct {
	uint8_t first;
	uint8_t last;
	uint8_t width;
	uint8_t height;
	const uint8_t (*bitmaps)[48];
} font_24 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
	,11
	,24
	,&acGUI_FontRobotoMonoMedium24_0020 /* address of first character */
};

